### PR TITLE
Changed footer

### PR DESCRIPTION
**Pull request by arguiot**
Added made with love at cryptools

### CODE REVIEW

**Comment by lucasgruwez** [comment]
Can you please send a screenshot?

**Comment by arguiot** [comment]
Ok @lucasgruwez I'll do it when I come back home

**Comment by arguiot** [comment]
@lucasgruwez Here it is:
capture d ecran 2018-02-14 a 18 36 19

**Comment by lucasgruwez** [comment]
Can you change `&#9829;` to `&hearts;`, as it makes more sense to anyone reading the code, and change the color to `#ea4433` please?

**Comment by arguiot** [comment]
@lucasgruwez done

**Pull request merged**
